[package]
name = "hokulea-host-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
# Hokulea and EigenDA
hokulea-proof.workspace = true
hokulea-client-bin.workspace = true
hokulea-eigenda.workspace = true

# Kona
kona-preimage = { workspace = true, features = ["std"] }
kona-host = { workspace = true, features = ["single"] }
kona-proof.workspace = true
kona-std-fpvm.workspace = true
kona-cli.workspace = true
kona-client.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }

# General
anyhow.workspace = true
tracing.workspace = true
reqwest.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
serde.workspace = true
tracing-subscriber.workspace = true
