[workspace]
resolver = "2"
members = ["bin/*", "crates/*"]

[profile.release-client-lto]
inherits = "release"
panic = "abort"
codegen-units = 1
lto = "fat"

[workspace.dependencies]
kona-client = { git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-host = { git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-derive = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false }
kona-driver = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-executor = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-mpt = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-preimage = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", features = [
    "rkyv",
    "serde",
] }
kona-proof = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-std-fpvm = { version = "0.2.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }
kona-providers-alloy = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16" }

# Workspace
hokulea-client-bin = { path = "bin/client", version = "0.1.0", default-features = false }
hokulea-client = { path = "crates/client", version = "0.1.0", default-features = false }
hokulea-eigenda = { path = "crates/eigenda", version = "0.1.0", default-features = false }
hokulea-proof = { path = "crates/proof", version = "0.1.0", default-features = false }
hokulea-compute-proof = { path = "crates/compute-proof", version = "0.1.0", default-features = false }

# Maili
kona-genesis = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false }
kona-protocol = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false }
kona-registry = { version = "0.3.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false }
kona-rpc = { version = "0.2.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false, features = [
    "serde",
] }
kona-cli = { version = "0.2.0", git = "https://github.com/op-rs/kona", tag = "kona-client/v0.1.0-beta.16", default-features = false }

# Alloy (Network)
alloy-signer-local = { version = "0.12.4" }
alloy-provider = { version = "0.12.4" }
alloy-transport = { version = "0.12.4" }
alloy-transport-http = { version = "0.12.4" }
alloy-contract = { version = "0.12.4" }
alloy-network = { version = "0.12.4" }

alloy-rlp = { version = "0.3.11", default-features = false }
alloy-trie = { version = "0.7.9", default-features = false }
alloy-eips = { version = "0.11.1", default-features = false }
alloy-serde = { version = "0.11.1", default-features = false }


alloy-consensus = { version = "0.12.4", default-features = false }

alloy-rpc-types = { version = "0.12.4", default-features = false }
alloy-rpc-client = { version = "0.12.4", default-features = false }

alloy-node-bindings = { version = "0.12.4", default-features = false }

alloy-rpc-types-engine = { version = "0.12.4", default-features = false }
alloy-rpc-types-beacon = { version = "0.12.4", default-features = false }

alloy-rpc-types-eth = { version = "0.12.4", default-features = false }
alloy-signer = { version = "0.12.4", default-features = false }

# Keccak with the SHA3 patch is more efficient than the default Keccak.
alloy-primitives = { version = "0.8.21", default-features = false, features = [
    "sha3-keccak",
] }
alloy-sol-types = { version = "0.8.21", default-features = false }
alloy-sol-macro = { version = "0.8.21", default-features = false }

# OP Alloy
op-alloy-consensus = { version = "0.11.0", default-features = false }
op-alloy-rpc-types = { version = "0.11.0", default-features = false }
op-alloy-rpc-types-engine = { version = "0.11.0", default-features = false }
op-alloy-network = { version = "0.11.0", default-features = false }

# General
lru = "0.13.0"
spin = "0.10.0"
rand = "0.9.0"
clap = "4.5.29"
tokio = { version = "1.44.2", features = ["full"] }
cfg-if = "1.0.0"
rstest = "0.24.0"
futures = "0.3.31"
reqwest = "0.12.12"
tempfile = "3.16.0"
arbitrary = "1.4.1"
async-trait = "0.1.86"
async-channel = "2.3.1"
linked_list_allocator = "0.10.5"
lazy_static = { version = "1.5.0", default-features = false }
bytes = "1.7.2"
num = "0.4"

# General
sha2 = { version = "0.10.8", default-features = false }
c-kzg = { version = "2.0.0", default-features = false }
anyhow = "1.0.86"
thiserror = "2.0.11"


rust-kzg-bn254-primitives = { version = "0.1.1", default-features = false }
rust-kzg-bn254-prover = { version = "0.1.1", default-features = false }
rust-kzg-bn254-verifier = { version = "0.1.1", default-features = false }

# EigenDA v2 struct
eigenda-v2-struct-rust =  { git = "https://github.com/bxue-l2/eigenda-v2-struct-rust", rev = "ee96955f6f7f42582c6340ce306ab31897fb34ae" }

ark-bn254 = "0.5.0"
ark-ff = { version = "0.5.0", features = ["parallel"] }

# Tracing
tracing-loki = "0.2.6"
tracing-subscriber = { version = "0.3.19", default-features = false }
tracing = { version = "0.1.41", default-features = false }

# Testing
pprof = "0.14.0"
arbtest = "0.3.2"
proptest = "1.6.0"
criterion = "0.5.1"

# Serialization
#rkyv = "0.8.10"
serde = { version = "1.0.217", default-features = false }
serde_json = { version = "1.0.138", default-features = false }

# Ethereum
unsigned-varint = "0.8.0"
revm = { version = "19.5.0", default-features = false }

# K/V database
rocksdb = { version = "0.22.0", default-features = false }

# ZKVM

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
