[package]
name = "hokulea-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus.workspace = true

kona-client.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-driver.workspace = true
kona-executor.workspace = true

hokulea-proof.workspace = true

tracing.workspace = true
