[package]
name = "hokulea-proof"
description = "Eigenda Proof SDK"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-preimage.workspace = true
kona-driver.workspace = true
kona-proof.workspace = true
kona-derive.workspace = true

hokulea-eigenda.workspace = true

eigenda-v2-struct-rust.workspace = true
rust-kzg-bn254-primitives.workspace = true
rust-kzg-bn254-verifier.workspace = true

ark-bn254.workspace = true
ark-ff.workspace = true

# Alloy
alloy-primitives.workspace = true

# Op Alloy
alloy-rlp.workspace = true
kona-protocol.workspace = true
kona-genesis.workspace = true
kona-rpc.workspace = true

# ZKVM

tracing.workspace = true

# General
async-trait.workspace = true
spin.workspace = true

#rkyv.workspace = true
serde.workspace = true

[features]
eigenda-view-proof = []